### PR TITLE
Improve code, make it work and all

### PR DESCRIPTION
**Pull request by fourjr**
Many changes have been made.

In the init of `Client `, the bot and token has to be provided as parameters. Documentation is not updated. 

Please note! The wrapper would only work after the `on_ready ` that discord.py provides

This wrapper does not support b1nzy's disco wrapper and only supports discord.py (both async and rewrite)

### CODE REVIEW

**Comment by ohlookitsAugust** [comment]
needs more `Client`

**Comment by fourjr** [comment]
@ohlookitsaugust what do you mean?

**Comment by FishyFing** [comment]
@fourjr he's memeing 😠

**Comment by fourjr** [comment]
thought it was :zoomeyes:

**Pull request merged**
